site_url: https://acm.xidian.edu.cn/docs
site_name: XDU ACM DOCS
nav:
  - 联系: contact.md
  - 资料: assets.md
  - 时间表:
    - 总览: schedule.md
    - 2022-2023: schedule/2022.md
  - 相关比赛:
    - 总览: contests.md
    - 校赛: campus.md
    - ICPC: contests/ICPC.md
    - CSP: contests/CSP.md
    - CCSP: contests/CCSP.md
    - GPLT-CCCC: contests/GPLT-CCCC.md
    - CCPC: contests/CCPC.md
  #- rating: rating.md
theme:
  name: readthedocs