site_url: https://acm.xidian.edu.cn/docs
site_name: XDU ACM DOCS
nav:
  - 联系: contact.md
  - 资料: assets.md
  - 时间表: schedule.md
  - 相关比赛: #contests.md
    - 总览: contests.md
    - 校赛: campus.md
  #- rating: rating.md
theme:
  name: readthedocs