site_url: https://acm.xidian.edu.cn/docs
site_name: XDU ACM DOCS
nav:
  - 联系: contact.md
  - 环境搭建: environment.md
  - Debug: debug.md
  - 常见编程错误列表: https://icpc.xidian.wiki/cce
  - 资料: assets.md
  - 2022-2023:
    - 基地活动: https://icpc.xidian.wiki/2022/schedule
    - 比赛: https://icpc.xidian.wiki/2022/contests
    #- 基地活动: 2022/schedule.md
    #- 比赛: 2022/contests.md
    #- 时间表: https://dokuwiki.gery.top/doku.php?id=2022-2023
  #- 活动: schedule.md
  - 相关比赛:
    - 总览: contests.md
    - 校赛: campus.md
    - ICPC: contests/ICPC.md
    - CSP: contests/CSP.md
    - CCSP: contests/CCSP.md
    - GPLT-CCCC: contests/GPLT-CCCC.md
    - CCPC: contests/CCPC.md
  #- rating: rating.md
theme:
  name: readthedocs
